name: Deploy Backend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Save private key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # Add server host key
          ssh-keyscan -p ${{ vars.SSH_PORT }} ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Server via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 \
              -o StrictHostKeyChecking=no \
              -p ${{ vars.SSH_PORT }} \
              ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "bash -s" << 'EOSSH'

            PROJECT=./htdocs/parkinourspot.com/backend

            # Load NVM for non-interactive shell
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Ensure Node is available
            echo "Using Node version: $(node -v)"
            echo "Using NPM version: $(npm -v)"

            if [ ! -d $PROJECT/.git ]; then
              echo "[SSH] Cloning repository..."
              git clone git@github.com:ehtwebaid/Car-Parking-Backend.git $PROJECT
            else
              echo "[SSH] Pulling latest changes..."
              cd $PROJECT
              git config --global --add safe.directory $PROJECT
              git pull origin main
            fi

            cd $PROJECT

            echo "[SSH] Installing dependencies..."
            npm install --legacy-peer-deps

            echo "[SSH] Starting/Restarting PM2..."
            pm2 start index.js --name app || pm2 restart app

            pm2 save

          EOSSH
