name: Deploy Backend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: |
          sudo apt-get update -y
          sudo apt-get install openssh-client -y

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          chmod 700 ~/.ssh
          ssh-keyscan -p ${{ vars.SSH_PORT }} ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server via SSH
        run: |
          ssh -p ${{ vars.SSH_PORT }} ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} 'bash -s' << 'EOSSH'

            # Node 18 is already installed on server

            if [ ! -d /htdocs/parkinourspot.com/backend/.git ]; then
              echo "[SSH] Cloning project repository..."
              git clone git@github.com:ehtwebaid/Car-Parking-Backend.git /htdocs/parkinourspot.com/backend
            else
              echo "[SSH] Pulling latest changes from main branch..."
              cd /htdocs/parkinourspot.com/backend
              git config --global --add safe.directory /htdocs/parkinourspot.com/backend
              git pull origin main
            fi

            cd /htdocs/parkinourspot.com/backend
            npm install
            pm2 start index.js --name app || pm2 restart app

          EOSSH
